// localStorage.clear()
const employees = [
  {
    id: 1,
    name: "Rohit",
    email: "employee1@example.com",
    password: "123",
    taskNumber: 4,
    taskType: "active",
    taskCount: { active: 2, newTask: 1, completed: 1, failed: 1 },
    tasks: [
      {
        taskTitle: "Update client database",
        taskDate: "2025-10-20",
        taskDescription: "Add new clients and verify existing contact details.",
        taskCategory: "Data Management",
        assignedBy: "Admin",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Prepare monthly report",
        taskDate: "2025-10-15",
        taskDescription: "Compile and format financial reports for Q3.",
        taskCategory: "Reporting",
        assignedBy: "Admin",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Fix login issue",
        taskDate: "2025-10-18",
        taskDescription: "Debug the authentication module for login errors.",
        taskCategory: "Development",
        assignedBy: "Admin",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Attend client meeting",
        taskDate: "2025-10-22",
        taskDescription: "Discuss project timelines and deliverables with client.",
        taskCategory: "Communication",
        assignedBy: "Admin",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    name: "Isha Patel",
    email: "employee2@example.com",
    password: "123",
    taskNumber: 5,
    taskType: "completed",
    taskCount: { active: 2, newTask: 1, completed: 2, failed: 1 },
    tasks: [
      {
        taskTitle: "Design landing page",
        taskDate: "2025-10-21",
        taskDescription: "Create a new responsive design for the home page.",
        taskCategory: "UI/UX Design",
        assignedBy: "Admin",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Optimize database",
        taskDate: "2025-10-10",
        taskDescription: "Improve query performance and indexing in the project DB.",
        taskCategory: "Backend",
        assignedBy: "Admin",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Code review",
        taskDate: "2025-10-19",
        taskDescription: "Review code submissions from team members.",
        taskCategory: "Development",
        assignedBy: "Admin",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Update API documentation",
        taskDate: "2025-10-24",
        taskDescription: "Ensure all endpoints are clearly documented.",
        taskCategory: "Documentation",
        assignedBy: "Admin",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Testing user flow",
        taskDate: "2025-10-26",
        taskDescription: "Perform QA testing on the main user journey.",
        taskCategory: "Testing",
        assignedBy: "Admin",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    name: "Rohan Mehta",
    email: "employee3@example.com",
    password: "123",
    taskNumber: 4,
    taskType: "active",
    taskCount: { active: 2, newTask: 1, completed: 1, failed: 1 },
    tasks: [
      {
        taskTitle: "Create marketing post",
        taskDate: "2025-10-23",
        taskDescription: "Design and schedule social media posts for Diwali campaign.",
        taskCategory: "Marketing",
        assignedBy: "Admin",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Team coordination",
        taskDate: "2025-10-17",
        taskDescription: "Organize weekly sprint meeting and share agenda.",
        taskCategory: "Management",
        assignedBy: "Admin",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Email campaign analysis",
        taskDate: "2025-10-13",
        taskDescription: "Review performance metrics from last month’s campaign.",
        taskCategory: "Analytics",
        assignedBy: "Admin",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Customer feedback review",
        taskDate: "2025-10-25",
        taskDescription: "Compile feedback from customer surveys.",
        taskCategory: "Support",
        assignedBy: "Admin",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    name: "Priya Singh",
    email: "employee4@example.com",
    password: "123",
    taskNumber: 4,
    taskType: "active",
    taskCount: { active: 1, newTask: 1, completed: 1, failed: 1 },
    tasks: [
      {
        taskTitle: "Deploy staging build",
        taskDate: "2025-10-19",
        taskDescription: "Push latest version to staging environment.",
        taskCategory: "DevOps",
        assignedBy: "Admin",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Bug triage meeting",
        taskDate: "2025-10-18",
        taskDescription: "Identify and prioritize bugs for sprint 15.",
        taskCategory: "QA",
        assignedBy: "Admin",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Performance optimization",
        taskDate: "2025-10-12",
        taskDescription: "Reduce app load time and optimize images.",
        taskCategory: "Performance",
        assignedBy: "Admin",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Server backup",
        taskDate: "2025-10-10",
        taskDescription: "Perform weekly data backup to secure cloud.",
        taskCategory: "Maintenance",
        assignedBy: "Admin",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 5,
    name: "Karan Verma",
    email: "employee5@example.com",
    password: "123",
    taskNumber: 4,
    taskType: "active",
    taskCount: { active: 2, newTask: 1, completed: 1, failed: 1 },
    tasks: [
      {
        taskTitle: "Design new logo",
        taskDate: "2025-10-22",
        taskDescription: "Create branding logo for new project launch.",
        taskCategory: "Design",
        assignedBy: "Admin",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Research competitors",
        taskDate: "2025-10-16",
        taskDescription: "Analyze competitor websites and product strategy.",
        taskCategory: "Research",
        assignedBy: "Admin",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Client presentation",
        taskDate: "2025-10-14",
        taskDescription: "Prepare slides for the quarterly project presentation.",
        taskCategory: "Presentation",
        assignedBy: "Admin",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Project documentation",
        taskDate: "2025-10-24",
        taskDescription: "Update and finalize documentation for the new release.",
        taskCategory: "Documentation",
        assignedBy: "Admin",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
];


const admin = [
  { id: 1, 
    email: "admin@example.com", 
    name: "Rahul", 
    password: "123" }
];



export const setLocalStorage =  ()=>{  
    localStorage.setItem('employees',JSON.stringify(employees))
    localStorage.setItem('admin',JSON.stringify(admin))
}

export const getLocalStorage =  ()=>{
    const employees = JSON.parse( localStorage.getItem('employees'))
    const admin = JSON.parse( localStorage.getItem('admin'))
    return {employees,admin}
}


